import type { Metadata } from "next";
import { Geist_Mono, Poppins, Playfair_Display } from "next/font/google";
import { ReduxProvider } from "@/src/redux/providers";
import { AuthProvider } from "@/src/contexts/AuthContext";
import Navbar from "@/src/app/components/Navbar";

import "./globals.css";
import { Toaster } from "react-hot-toast";

const playfairDisplay = Playfair_Display({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const poppinsSans = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsSans.variable} ${geistMono.variable} ${playfairDisplay.variable} antialiased`}
      >
        <Toaster />
        <ReduxProvider>
          <AuthProvider>
            <Navbar />
            <main className="pt-16">{children}</main>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
